import type { Address } from "viem";

export const APP_CONFIG = {
  appName: "BOTCOIN Pool Console",
  privyAppId: process.env.NEXT_PUBLIC_PRIVY_APP_ID ?? "",
  defaultPoolAddress: "0xCC804C0Ea1E1100341CaF8993061A96ED267eae2" as Address,
  operatorAddress: "0x514516deE6A11ce0AE7E2769f272e8dB7f95cA40" as Address,
  miningAddress: "0xcF5F2D541EEb0fb4cA35F1973DE5f2B02dfC3716" as Address,
  bonusEpochAddress: "0xA185fE194A7F603b7287BC0abAeBA1b896a36Ba8" as Address,
  botcoinAddress: "0xA601877977340862Ca67f816eb079958E5bd0BA3" as Address,
  feeRecipientAddress: "0x514516deE6A11ce0AE7E2769f272e8dB7f95cA40" as Address,
  chainId: 8453,
  deploymentStartBlock: 43_190_261n,
  receiptSubmitSelector: "0xf9b5aac1" as const,
  maxEpochsPerClaim: 20,
  polling: {
    headMs: 4_000,
    userMs: 5_000,
  },
  // Chainlist Base mainnet rank snapshot from 2026-03-13, keeping only unique HTTPS endpoints
  // from the visible top-20 set that answered browser-side eth_chainId probes without CORS issues.
  rpcUrls: [
    "https://base.llamarpc.com",
    "https://api.zan.top/base-mainnet",
    "https://base.api.pocket.network",
    "https://base-mainnet.gateway.tatum.io",
    "https://developer-access-mainnet.base.org",
    "https://base.lava.build",
    "https://mainnet.base.org",
    "https://rpc.sentio.xyz/base",
    "https://base-public.nodies.app",
    "https://base.meowrpc.com",
    "https://1rpc.io/base",
    "https://base.rpc.subquery.network/public",
    "https://base-rpc.publicnode.com",
    "https://gateway.tenderly.co/public/base",
    "https://base.drpc.org",
    "https://base-mainnet.public.blastapi.io",
  ],
  privyWalletList: [
    "metamask",
    "coinbase_wallet",
    "detected_ethereum_wallets",
    "wallet_connect",
  ] as const,
  liveAbiNames: [
    "deposit",
    "stakeAvailablePrincipal",
    "submitToMining",
    "triggerClaim",
    "triggerBonusClaim",
    "claimMyRewards",
    "unstakeAtEpochEnd",
    "completeWithdraw",
    "claimMyShare",
    "processEpochCheckpoint",
  ] as const,
  hiddenLegacyAbiNames: [
    "submitReceiptToMining",
    "claimRewards",
    "claimBonusRewards",
    "claimUser",
    "withdrawPrincipal",
    "finalizeWithdraw",
  ] as const,
} as const;

export const FLOW_LABELS = [
  "Deposit BOTCOIN into the pool",
  "Pool stakes available principal",
  "Operator solves the off-chain challenge",
  "Operator submits mining calldata",
  "Pool forwards receipt to Mining V2",
  "Claim regular rewards into the pool",
  "Pool receives regular BOTCOIN rewards",
  "Claim bonus rewards into the pool",
  "Pool receives bonus BOTCOIN rewards",
  "Pool records reward distribution",
  "Depositor claims rewards",
  "Anyone can request epoch-end unstake",
  "Anyone can complete cooldown withdraw",
  "Depositor claims principal or prepares to redeposit",
] as const;
